#!/usr/bin/env bash
# Display a list of all currently running processes in a hierarchical format. Includes user, PID, CPU and memory usage, TTY, process state, start time, and command
ps -eo user:12,pid,pcpu,pmem,vsz,rss,tty,stat,start,time,cmd --forest
